<?php

return [
  'title' => 'Log in',
  'action' => 'Log in',
  'login_redirect' => 'Don\'t have an account?',
  'register_redirect' => 'Already have an account?',
  'failed' => 'These credentials do not match our records.',
  'password' => 'These credentials do not match our records.',
  'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
  'name' => 'Name',
  'provider' => 'This account is linked with :provider account.',
  'forgot_password_description' => 'Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.',
  'confirm_password_description' => 'This is a secure area of the application. Please confirm your password before continuing.',
  'profile_description' => 'Update your account\'s profile information and email address.',
  'update_password_description' => 'Ensure your account is using a long, random password to stay secure.',
  'delete_account_description' => 'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.',
  'delete_account_confirmation' => 'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',
  'set_password_description' => 'You logged-in using 3rd party provider such as Google, Apple or Linkedin. To be able to access platform directly set a password.',
  'onboarding_teacher_question' => 'Please tell us if you would like to teach or you are looking for tutors?',
  'onboarding_teacher_title' => 'Welcome to our platform :first_name!',
  'onboarding_not_teacher' => 'Looking for Teachers',
  'onboarding_is_teacher' => 'I want to Teach',
  'approval_notice' => 'Your image update is under review. It will be visible as soon as it is approved.',
  'approval_denied_notice' => 'Your image update has been denied. Please upload a new image that complies with our guidelines.',
  'update_profile_photo' => 'Update Profile Photo',
  'update_email_action' => 'Confirm Email',
  'update_email_description' => 'We were not able to detect email from your authentication provider. Please type in your email to continue.',
  'update_email_failed' => 'Failed to update email. It probably already exists in our system.',
  'login_meta_title' => 'Login to Clasora - Connect with Trusted Tutors Worldwide or Start Teaching',
  'login_meta_keywords' => 'Clasora login, tutor login, student login, free tutoring platform, online learning login, language tutors login',
  'login_meta_description' => 'Log in to your Clasora account to find and connect with experienced tutors in multiple languages. 100% free for both students and teachers.',
  'register_meta_title' => 'Join Clasora - Free Platform to Find or Become a Tutor',
  'register_meta_keywords' => 'Clasora registration, sign up tutors, sign up students, become a tutor, find a tutor, free tutoring site, online lessons',
  'register_meta_description' => 'Register for free on Clasora to find the perfect tutor or start offering lessons worldwide. No fees, no commissions – just learning and teaching.',
  'forgot_password_meta_title' => 'Reset Your Password - Clasora Tutoring Platform',
  'forgot_password_meta_description' => 'Forgot your password? Easily reset your Clasora account credentials and get back to learning or teaching. Fast and secure recovery process.',
  'forgot_password_meta_keywords' => 'Clasora password reset, forgot password, recover account, reset login, tutoring account recovery, Clasora forgot password',
];
