<?php

return [
  'description_1' => 'Registration and posting ads will always be free.',
  'native_speakers_section' => 'Want to learn a language from a native speaker or foreign tutor? Check out these posts.',
  'choose' => 'Choose',
  'chosen' => 'Chosen',
  'remove' => 'Remove',
  'subject' => 'Subject',
  'choose_subject' => 'Choose subject',
  'choose_tag' => 'Choose tag',
  'choose_language' => 'Choose language',
  'levels_certifications' => 'Levels & certifications',
  'tutor_speaks' => 'Tutor speaks',
  'default' => 'Default',
  'class_location' => 'Location of the class',
  'blogs' => 'Articles written by tutor',
  'author' => 'Author',
  'alternative_language_section' => 'Here are some foreign posts you might be interested in.',
  // Welcome page sections
  'why_choose_title' => 'Why Choose Clasora?',
  'why_choose_description' => 'Clasora connects you with tutors for <strong>private, 1-on-1 lessons</strong> — both <strong>online and in person</strong>. Learn at your own pace, from passionate educators who care.',
  'why_choose_personalized_title' => '🎯 Personalized Learning',
  'why_choose_personalized_text' => 'Every tutor sets their own teaching style. Whether you’re learning a language, preparing for exams, or picking up a new skill — find someone who fits you.',
  'why_choose_affordable_title' => '💸 Transparent & Affordable',
  'why_choose_affordable_text' => 'No subscriptions, no hidden fees. Pay only for what you book. Tutors keep 100% of what they earn.',
  'why_choose_online_local_title' => '🌍 Online & Local Options',
  'why_choose_online_local_text' => 'Prefer in-person lessons? Some tutors offer local sessions too. Choose what works best for you.',
  'how_it_works_title' => 'How It Works',
  'how_it_works_1_title' => '1. Search',
  'how_it_works_1_text' => 'Find a subject or skill you want to learn. Use filters to narrow down your preferences.',
  'how_it_works_2_title' => '2. Choose',
  'how_it_works_2_text' => 'Compare tutors by reviews, prices, languages, and lesson types — online or in person.',
  'how_it_works_3_title' => '3. Book',
  'how_it_works_3_text' => 'Book a 1-on-1 lesson that fits your schedule and start learning right away.',
  'for_tutors_title' => 'For Tutors',
  'for_tutors_description' => 'Share your knowledge. Teach your way. Clasora gives you the tools to grow your tutoring business — free of charge.',
  'for_tutors_benefit_1' => 'No commissions — keep 100% of your earnings',
  'for_tutors_benefit_2' => 'Create a public profile and write your own blog',
  'for_tutors_benefit_3' => 'Offer online or in-person lessons',
  'for_tutors_cta' => 'Start Teaching',
  
];
