<?php

return [
  'title' => 'Anmelden',
  'action' => 'Anmelden',
  'login_redirect' => 'Sie haben noch kein Konto?',
  'register_redirect' => 'Sie haben bereits ein Konto?',
  'failed' => 'Diese Zugangsdaten stimmen nicht mit unseren Datensätzen überein.',
  'password' => 'Diese Zugangsdaten stimmen nicht mit unseren Datensätzen überein.',
  'throttle' => 'Zu viele Anmeldeversuche. Bitte versuchen Sie es in :seconds Sekunden erneut.',
  'name' => 'Name',
  'provider' => 'Dieses Konto ist mit dem Konto von :provider verknüpft.',
  'forgot_password_description' => 'Haben Sie Ihr Passwort vergessen? Kein Problem. Teilen Sie uns einfach Ihre E-Mail-Adresse mit, und wir senden Ihnen einen Link zum Zurücksetzen des Passworts, mit dem Sie ein neues Passwort erstellen können.',
  'confirm_password_description' => 'Dies ist ein gesicherter Bereich der Anwendung. Bitte bestätigen Sie Ihr Passwort, um fortzufahren.',
  'profile_description' => 'Aktualisieren Sie die Profildaten und die E-Mail-Adresse Ihres Kontos.',
  'update_password_description' => 'Achten Sie darauf, dass Ihr Konto ein langes und zufälliges Passwort verwendet, um sicher zu bleiben.',
  'delete_account_description' => 'Sobald Ihr Konto gelöscht ist, werden alle Ressourcen und Daten dauerhaft entfernt. Bitte laden Sie alle Daten oder Informationen, die Sie behalten möchten, herunter, bevor Sie Ihr Konto löschen.',
  'delete_account_confirmation' => 'Sobald Ihr Konto gelöscht ist, werden alle Ressourcen und Daten dauerhaft entfernt. Bitte geben Sie Ihr Passwort ein, um zu bestätigen, dass Sie Ihr Konto dauerhaft löschen möchten.',
  'set_password_description' => 'Sie haben sich mit einem Drittanbieter wie Google, Apple oder LinkedIn angemeldet. Um direkt auf die Plattform zugreifen zu können, legen Sie ein Passwort fest.',
  'onboarding_teacher_question' => 'Bitte teilen Sie uns mit, ob Sie unterrichten möchten oder ob Sie nach Lehrern suchen?',
  'onboarding_teacher_title' => 'Willkommen auf unserer Plattform, :first_name!',
  'onboarding_not_teacher' => 'Lehrer suchen',
  'onboarding_is_teacher' => 'Ich möchte unterrichten',
  'approval_notice' => 'Ihre Bildaktualisierung wird überprüft. Es wird sichtbar, sobald es genehmigt wurde.',
  'update_profile_photo' => 'Profilbild aktualisieren',
  'update_email_action' => 'E-Mail bestätigen',
  'update_email_description' => 'Wir konnten keine E-Mail-Adresse von Ihrem Authentifizierungsanbieter erkennen. Bitte geben Sie Ihre E-Mail-Adresse ein, um fortzufahren.',
  'update_email_failed' => 'E-Mail-Aktualisierung fehlgeschlagen. Sie existiert wahrscheinlich bereits in unserem System.',
  'login_meta_title' => 'Bei Clasora anmelden - Verbinden Sie sich mit vertrauenswürdigen Tutoren weltweit oder beginnen Sie zu unterrichten',
  'login_meta_keywords' => 'Clasora Anmeldung, Tutor Anmeldung, Schüler Anmeldung, kostenlose Nachhilfe-Plattform, Online-Lernen Anmeldung, Sprachlehrer Anmeldung',
  'login_meta_description' => 'Melden Sie sich bei Ihrem Clasora-Konto an, um erfahrene Tutoren in verschiedenen Sprachen zu finden und sich mit ihnen zu verbinden. 100% kostenlos für Schüler und Lehrer.',
  'register_meta_title' => 'Bei Clasora registrieren - Kostenlose Plattform um Tutoren zu finden oder selbst einer zu werden',
  'register_meta_keywords' => 'Clasora Registrierung, Tutoren anmelden, Schüler anmelden, Tutor werden, Tutor finden, kostenlose Nachhilfe-Seite, Online-Unterricht',
  'register_meta_description' => 'Registrieren Sie sich kostenlos bei Clasora, um den perfekten Tutor zu finden oder selbst weltweite Unterrichtsstunden anzubieten. Keine Gebühren, keine Provisionen – nur Lernen und Lehren.',
  'forgot_password_meta_title' => 'Passwort zurücksetzen - Clasora Nachhilfe-Plattform',
  'forgot_password_meta_description' => 'Passwort vergessen? Setzen Sie Ihre Clasora-Kontodaten einfach zurück und kehren Sie zum Lernen oder Unterrichten zurück. Schneller und sicherer Wiederherstellungsprozess.',
  'forgot_password_meta_keywords' => 'Clasora Passwort zurücksetzen, Passwort vergessen, Konto wiederherstellen, Anmeldung zurücksetzen, Nachhilfe-Konto Wiederherstellung, Clasora Passwort vergessen',
];
