<?php

return [
  'description_1' => 'Die Registrierung und das Veröffentlichen von Anzeigen ist immer kostenlos.',
  'native_speakers_section' => 'Möchten Sie eine Sprache von einem Muttersprachler oder einem ausländischen Lehrer lernen? Schauen Sie sich diese Beiträge an.',
  'choose' => 'Wählen Sie',
  'chosen' => 'Ausgewählt',
  'remove' => 'Entfernen',
  'subject' => 'Fach',
  'choose_subject' => 'Wählen Sie ein Fach',
  'choose_tag' => 'Wählen Sie ein Tag',
  'choose_language' => 'Wählen Sie eine Sprache',
  'levels_certifications' => 'Niveaus und Zertifikate',
  'tutor_speaks' => 'Der Tutor spricht',
  'default' => 'Standard',
  'class_location' => 'Standort des Kurses',
  'blogs' => 'Artikel des Tutors',
  'author' => 'Autor',
  'alternative_language_section' => 'Hier sind einige ausländische Beiträge, die Sie interessieren könnten.',
  'why_choose_title' => 'Warum Clasora wählen?',
  'why_choose_description' => 'Clasora verbindet Sie mit Tutoren für private Einzelstunden – sowohl online als auch vor Ort. Lernen Sie in Ihrem eigenen Tempo mit engagierten Lehrkräften, denen Ihr Fortschritt am Herzen liegt.',
  'why_choose_personalized_title' => 'Individuelles Lernen',
  'why_choose_personalized_text' => 'Jeder Tutor hat seinen eigenen Stil. Egal ob Sie eine Sprache lernen, sich auf Prüfungen vorbereiten oder neue Fähigkeiten erwerben möchten – finden Sie die passende Person für sich.',
  'why_choose_affordable_title' => 'Transparent & Preiswert',
  'why_choose_affordable_text' => 'Keine Abos, keine versteckten Kosten. Sie zahlen nur für gebuchte Stunden. Tutoren behalten 100% ihres Verdienstes.',
  'why_choose_online_local_title' => 'Online & vor Ort',
  'why_choose_online_local_text' => 'Sie bevorzugen Präsenzunterricht? Viele Tutoren bieten auch lokale Termine an. Wählen Sie, was am besten zu Ihnen passt.',
  'how_it_works_title' => 'So funktioniert es',
  'how_it_works_1_title' => '1. Suchen',
  'how_it_works_1_text' => 'Finden Sie das Fach oder die Fähigkeit, die Sie lernen möchten. Nutzen Sie Filter, um Ihre Auswahl einzugrenzen.',
  'how_it_works_2_title' => '2. Wählen',
  'how_it_works_2_text' => 'Vergleichen Sie Tutoren nach Bewertungen, Preisen, Sprachen und Unterrichtsarten – online oder vor Ort.',
  'how_it_works_3_title' => '3. Buchen',
  'how_it_works_3_text' => 'Buchen Sie eine Einzelstunde, die zu Ihrem Zeitplan passt, und starten Sie direkt mit dem Lernen.',
  'for_tutors_title' => 'Für Tutoren',
  'for_tutors_description' => 'Teilen Sie Ihr Wissen. Unterrichten Sie auf Ihre Weise. Clasora bietet Ihnen die Werkzeuge, um Ihr Nachhilfe-Business kostenlos auszubauen.',
  'for_tutors_benefit_1' => 'Keine Provisionen – Sie behalten 100% Ihres Verdienstes',
  'for_tutors_benefit_2' => 'Erstellen Sie ein öffentliches Profil und schreiben Sie Ihren eigenen Blog',
  'for_tutors_benefit_3' => 'Bieten Sie Online- oder Präsenzunterricht an',
  'for_tutors_cta' => 'Jetzt unterrichten',
];
