<?php

return [
  'title' => 'Prijava',
  'action' => 'Prijava',
  'login_redirect' => 'Še nimate računa?',
  'register_redirect' => 'Že imate račun?',
  'failed' => 'Ovi kredencijali se ne poklapaju sa našim zapisima.',
  'password' => 'Uneta lozinka je netačna.',
  'throttle' => 'Previse poskusajev prijave. Molimo poskusajte ponovo za :seconds sekundi.',
  'name' => 'Ime',
  'provider' => 'Ovaj nalog je povezan sa :provider nalogom.',
  'forgot_password_description' => 'Ste pozabili geslo? Ni problema. Sporočite nam svoj email naslov in poslali vam bomo povezavo za ponastavitev gesla.',
  'confirm_password_description' => 'To je varno območje aplikacije. Pred nadaljevanjem potrdite svoje geslo.',
  'profile_description' => 'Posodobite informacije na profilu in e-poštni naslov računa.',
  'update_password_description' => 'Poskrbite, da vaš račun uporablja dolgo, naključno geslo, da ostanete varni.',
  'delete_account_description' => 'Ko bo vaš račun izbrisan, bodo vsi njegovi viri in podatki trajno izbrisani. Preden izbrišete svoj račun, prenesite vse podatke ali informacije, ki jih želite obdržati.',
  'delete_account_confirmation' => 'Ko bo račun izbrisan, bodo vsi njegovi viri in podatki trajno izbrisani. Vnesite svoje geslo, da potrdite, da želite trajno izbrisati svoj račun.',
  'set_password_description' => 'Prijavili ste se z uporabo ponudnika tretjih oseb, kot so Google, Apple ali Linkedin. Da boste lahko neposredno dostopali do platforme, nastavite geslo.',
  'onboarding_teacher_question' => 'Povejte nam, ali bi radi poučevali ali iščete mentorje?',
  'onboarding_teacher_title' => 'Dobrodošli na naši platformi, :first_name!',
  'onboarding_not_teacher' => 'Iščem učitelje',
  'onboarding_is_teacher' => 'Želim poučevati',
  'approval_notice' => 'Vaša posodobitev slike je v pregledu. Vidna bo, takoj ko bo odobrena.',
  'approval_denied_notice' => 'Vaša posodobitev slike je bila zavrnjena. Prosimo, naložite novo sliko, ki ustreza našim smernicam.',
  'update_profile_photo' => 'Posodobi profilno sliko',
  'update_email_action' => 'Potrdi e-pošto',
  'update_email_description' => 'Nismo mogli zaznati e-poštnega naslova iz vašega ponudnika preverjanja pristnosti. Vnesite svoj e-poštni naslov za nadaljevanje.',
  'update_email_failed' => 'Posodobitev e-pošte ni uspela. Verjetno že obstaja v našem sistemu.',
  'login_meta_title' => 'Prijavite se v Clasoro - Povežite se z zaupanja vrednimi mentorji po svetu ali začnite poučevati',
  'login_meta_keywords' => 'Clasora prijava, prijava mentor, prijava študent, brezplačna platforma mentorstva, prijava spletno učenje, prijava jezikovni mentorji',
  'login_meta_description' => 'Prijavite se v svoj Clasora račun, da poiščete in se povežete z izkušenimi mentorji v več jezikih. 100% brezplačno za študente in učitelje.',
  'register_meta_title' => 'Pridružite se Clasori - Brezplačna platforma za iskanje ali postajanje mentorja',
  'register_meta_keywords' => 'Clasora registracija, registracija mentorji, registracija študenti, postani mentor, najdi mentorja, brezplačna stran mentorstva, spletne ure',
  'register_meta_description' => 'Registrirajte se brezplačno na Clasori, da poiščete popolnega mentorja ali začnete ponujati ure po svetu. Brez stroškov, brez provizij - samo učenje in poučevanje.',
  'forgot_password_meta_title' => 'Ponastavite svoje geslo - Clasora platforma mentorstva',
  'forgot_password_meta_description' => 'Pozabili geslo? Enostavno ponastavite poverilnice svojega Clasora računa in se vrnite k učenju ali poučevanju. Hiter in varen postopek obnovitve.',
  'forgot_password_meta_keywords' => 'Clasora ponastavitev gesla, pozabil geslo, obnovi račun, ponastavi prijavo, obnovitev računa mentorstva, Clasora pozabil geslo',
];
