<?php

return [
  'description_1' => 'Registracija in objava oglasov bosta vedno brezplačni.',
  'native_speakers_section' => 'Se želite naučiti jezika od učitelja, ki uporablja ta jezik kot materni, od rojstva naprej? Ali hočete inštruktorja, ki se je tega jezika priučil kot tujega? Oglejte si te objave.',
  'choose' => 'Izberi',
  'chosen' => 'Izbrano',
  'remove' => 'Odstrani',
  'subject' => 'Predmet',
  'choose_subject' => 'Izberite predmet',
  'choose_tag' => 'Izberite oznako',
  'choose_language' => 'Izberite jezik',
  'levels_certifications' => 'Stopnje in certifikati',
  'tutor_speaks' => 'Učitelj govori',
  'default' => 'Privzeto',
  'class_location' => 'Lokacija razreda',
  'blogs' => 'Članki predavateljev',
  'author' => 'Avtor',
  'alternative_language_section' => 'Tukaj je nekaj tujih objav, ki bi vas lahko zanimale.',
  'why_choose_title' => 'Zakaj izbrati Clasora?',
  'why_choose_description' => 'Clasora vas poveže z učitelji za zasebne, individualne ure — tako online kot v živo. Učite se v svojem tempu, z učitelji, ki jim je mar za vaš napredek.',
  'why_choose_personalized_title' => 'Prilagojeno učenje',
  'why_choose_personalized_text' => 'Vsak učitelj ima svoj način poučevanja. Ne glede na to, ali se učite jezika, pripravljate na izpite ali pridobivate nove veščine — poiščite nekoga, ki vam ustreza.',
  'why_choose_affordable_title' => 'Pregledno in ugodno',
  'why_choose_affordable_text' => 'Brez naročnin, brez skritih stroškov. Plačate le za rezervirane ure. Učitelji prejmejo 100% zaslužka.',
  'why_choose_online_local_title' => 'Online in v živo',
  'why_choose_online_local_text' => 'Raje obiskujete ure v živo? Nekateri učitelji ponujajo tudi lokalne termine. Izberite, kar vam najbolj ustreza.',
  'how_it_works_title' => 'Kako deluje',
  'how_it_works_1_title' => '1. Poiščite',
  'how_it_works_1_text' => 'Poiščite predmet ali veščino, ki jo želite osvojiti. Uporabite filtre za natančnejši izbor.',
  'how_it_works_2_title' => '2. Izberite',
  'how_it_works_2_text' => 'Primerjajte učitelje po ocenah, cenah, jezikih in načinu pouka — online ali v živo.',
  'how_it_works_3_title' => '3. Rezervirajte',
  'how_it_works_3_text' => 'Rezervirajte individualno uro, ki vam časovno ustreza, in začnite z učenjem takoj.',
  'for_tutors_title' => 'Za učitelje',
  'for_tutors_description' => 'Delite svoje znanje. Poučujte na svoj način. Clasora vam nudi orodja za rast vašega učiteljskega posla — brezplačno.',
  'for_tutors_benefit_1' => 'Brez provizij — 100% zaslužka ostane vam',
  'for_tutors_benefit_2' => 'Ustvarite javni profil in pišite svoj blog',
  'for_tutors_benefit_3' => 'Poučujte online ali v živo',
  'for_tutors_cta' => 'Začnite poučevati',
];
