<?php

return [
  'register' => 'региструј-се',
  'about' => 'о-нама',
  'login' => 'пријави-се',
  'tutoring' => 'предавање',
  'post' => 'оглас',
  'posts' => 'огласи',
  'my-posts' => 'моји-огласи',
  'my' => 'моји',
  'create' => 'креирај',
  'messages' => 'поруке',
  'group' => 'група',
  'forgot-password' => 'заборављена-лозинка',
  'reset-password' => 'обнови-лозинку',
  'verify-email' => 'потврди-емаил',
  'verification-notification' => 'потврдно-обавестење',
  'email' => 'емаил',
  'confirm-password' => 'потврди-лозинку',
  'password' => 'лозинка',
  'logout' => 'одјави-се',
  'report' => 'пријави',
  'lesson' => 'цас',
  'updates' => 'азурирања',
  'frequently-asked-questions' => 'најцесце-постављена-питања',
  'privacy-policy' => 'политика-приватности',
  'cookie-policy' => 'политика-употребе-колацица',
  'contact-us' => 'контактирајте-нас',
  'terms-of-service' => 'услови-корисцења',
  'update-email' => 'азурирајте-емаил',
];
