<?php

return [
  'title' => 'Zaloguj się',
  'action' => 'Zaloguj się',
  'login_redirect' => 'Nie masz konta?',
  'register_redirect' => 'Masz już konto?',
  'failed' => 'Te dane uwierzytelniające nie pasują do naszych zapisów. ',
  'password' => 'Te dane uwierzytelniające nie pasują do naszych zapisów. ',
  'throttle' => 'Zbyt wiele prób logowania. Spróbuj ponownie za :sekundy.',
  'name' => 'Nazwa',
  'provider' => 'Konto jest powiązane: provider account.',
  'forgot_password_description' => 'Nie pamiętasz hasła? Nie ma sprawy. Podaj swój adres e-mail, a my wyślemy ci link do zresetowania hasła.',
  'confirm_password_description' => 'To jest bezpieczna strefa aplikacji. Potwierdź swoje hasło, aby kontynuować.',
  'profile_description' => 'Zaktualizuj swoje dane i adres e-mail w profilu.',
  'update_password_description' => 'Upewnij się, że używasz długiego, losowego hasła, aby zachować bezpieczeństwo.',
  'delete_account_description' => 'Po usunięciu konta wszystkie zapisy i dane zostaną trwale usunięte. Przed usunięciem konta pobierz wszelkie dane lub informacje, które chcesz zachować.',
  'delete_account_confirmation' => 'Po usunięciu konta wszystkie dane zostaną trwale usunięte. Wprowadź hasło, żeby potwierdzić, że chcesz całkowicie usunąć swoje konto.',
  'set_password_description' => 'Zalogowałeś się za pomocą zewnętrznego dostawcy, takiego jak Google, Apple lub LinkedIn. Aby uzyskać bezpośredni dostęp do platformy, ustaw hasło.',
  'onboarding_teacher_question' => 'Powiedz nam czy chcesz uczyć czy szukasz korepetytorów?',
  'onboarding_teacher_title' => 'Witamy na naszej platformie: first_name!',
  'onboarding_not_teacher' => 'Szukam nauczycieli',
  'onboarding_is_teacher' => 'Chcę uczyć',
  'approval_notice' => 'Twoja aktualizacja zdjęcia jest w trakcie weryfikacji. Będzie widoczna, gdy tylko zostanie zatwierdzona.',
  'approval_denied_notice' => 'Twoja aktualizacja zdjęcia została odrzucona. Proszę, prześlij nowe zdjęcie zgodne z naszymi wytycznymi.',
  'update_profile_photo' => 'Zaktualizuj zdjęcie profilowe',
  'update_email_action' => 'Potwierdź e-mail',
  'update_email_description' => 'Nie udało się nam wykryć adresu e-mail od Twojego dostawcy uwierzytelniania. Wprowadź swój adres e-mail, aby kontynuować.',
  'update_email_failed' => 'Nie udało się zaktualizować adresu e-mail. Prawdopodobnie już istnieje w naszym systemie.',
  'login_meta_title' => 'Zaloguj się do Clasora - Połącz się z zaufanymi korepetytorami na całym świecie lub zacznij uczyć',
  'login_meta_keywords' => 'Clasora logowanie, logowanie korepetytor, logowanie uczeń, darmowa platforma korepetycji, logowanie nauka online, logowanie nauczyciele języków',
  'login_meta_description' => 'Zaloguj się do swojego konta Clasora, aby znaleźć i połączyć się z doświadczonymi korepetytorami w wielu językach. 100% darmowe dla uczniów i nauczycieli.',
  'register_meta_title' => 'Dołącz do Clasora - Darmowa platforma do znajdowania lub zostania korepetytorem',
  'register_meta_keywords' => 'Clasora rejestracja, rejestracja korepetytorzy, rejestracja uczniowie, zostań korepetytorem, znajdź korepetytora, darmowy serwis korepetycji, lekcje online',
  'register_meta_description' => 'Zarejestruj się bezpłatnie w Clasora, aby znaleźć idealnego korepetytora lub zacząć oferować lekcje na całym świecie. Bez opłat, bez prowizji - tylko nauka i nauczanie.',
  'forgot_password_meta_title' => 'Resetuj hasło - Platforma korepetycji Clasora',
  'forgot_password_meta_description' => 'Zapomniałeś hasła? Łatwo zresetuj dane logowania do konta Clasora i wróć do nauki lub nauczania. Szybki i bezpieczny proces odzyskiwania.',
  'forgot_password_meta_keywords' => 'Clasora reset hasła, zapomniałem hasła, odzyskaj konto, resetuj logowanie, odzyskiwanie konta korepetycji, Clasora zapomniałem hasła',
];
