<?php

return [
  'description_1' => 'Chcesz nauczyć się języka od rodzimego mówcy lub obcokrajowcy? Sprawdź te posty',
  'native_speakers_section' => 'Chcesz nauczyć się języka z native speakerem lub nauczycielem niebędącym nosicielem języka? Sprawdź te wpisy.',
  'choose' => 'Wybierz',
  'chosen' => 'Wybrany',
  'remove' => 'Usuń',
  'subject' => 'Przedmiot',
  'choose_subject' => 'Wybierz przedmiot',
  'choose_tag' => 'Wybierz tag',
  'choose_language' => 'Wybierz język',
  'levels_certifications' => 'Poziomy i certyfikaty',
  'tutor_speaks' => 'Nauczyciel mówi',
  'default' => 'Domyślnie',
  'class_location' => 'Lokalizacja zajęć',
  'blogs' => 'Artykuły nauczyciela',
  'author' => 'Autor',
  'alternative_language_section' => 'Oto kilka zagranicznych postów, którymi możesz być zainteresowany.',
  'why_choose_title' => 'Dlaczego Clasora?',
  'why_choose_description' => 'Clasora łączy Cię z nauczycielami do prywatnych, indywidualnych lekcji — zarówno online, jak i stacjonarnie. Ucz się w swoim tempie, z pasjonatami, którym zależy na Twoim rozwoju.',
  'why_choose_personalized_title' => 'Indywidualne podejście',
  'why_choose_personalized_text' => 'Każdy nauczyciel ma swój styl. Niezależnie czy uczysz się języka, przygotowujesz do egzaminów czy zdobywasz nowe umiejętności — znajdź osobę, która Ci odpowiada.',
  'why_choose_affordable_title' => 'Przejrzyście i bez ukrytych kosztów',
  'why_choose_affordable_text' => 'Brak abonamentów, brak ukrytych opłat. Płacisz tylko za to, co rezerwujesz. Nauczyciele otrzymują 100% wynagrodzenia.',
  'why_choose_online_local_title' => 'Online i stacjonarnie',
  'why_choose_online_local_text' => 'Wolisz lekcje na żywo? Wielu nauczycieli oferuje też zajęcia stacjonarne. Wybierz, co Ci pasuje.',
  'how_it_works_title' => 'Jak to działa',
  'how_it_works_1_title' => '1. Wyszukaj',
  'how_it_works_1_text' => 'Znajdź przedmiot lub umiejętność, którą chcesz opanować. Skorzystaj z filtrów, by zawęzić wybór.',
  'how_it_works_2_title' => '2. Wybierz',
  'how_it_works_2_text' => 'Porównaj nauczycieli według opinii, cen, języków i rodzaju lekcji — online lub stacjonarnie.',
  'how_it_works_3_title' => '3. Zarezerwuj',
  'how_it_works_3_text' => 'Zarezerwuj indywidualną lekcję w dogodnym terminie i zacznij naukę od razu.',
  'for_tutors_title' => 'Dla nauczycieli',
  'for_tutors_description' => 'Podziel się wiedzą. Ucz na własnych zasadach. Clasora daje Ci narzędzia do rozwoju — całkowicie za darmo.',
  'for_tutors_benefit_1' => 'Brak prowizji — 100% wynagrodzenia trafia do Ciebie',
  'for_tutors_benefit_2' => 'Stwórz publiczny profil i prowadź własnego bloga',
  'for_tutors_benefit_3' => 'Prowadź lekcje online lub stacjonarnie',
  'for_tutors_cta' => 'Zacznij uczyć',
];
