<?php

return [
  'register' => 'reyestratsiya',
  'about' => 'pro-nas',
  'login' => 'vkhid',
  'tutoring' => 'vikladatska-diyalnist',
  'post' => 'ogoloshennya',
  'posts' => 'spisok-ogoloshen',
  'my-posts' => 'moyi-ogoloshennya',
  'my' => 'miy',
  'create' => 'stvoriti',
  'messages' => 'povidomlennya',
  'group' => 'grupa',
  'forgot-password' => 'zabuli-parol',
  'reset-password' => 'skidannya-parolya',
  'verify-email' => 'pidtverdzhennya-elektronnoyi-poshti',
  'verification-notification' => 'povidomlennya-pro-pidtverdzhennya',
  'email' => 'elektronna-poshta',
  'confirm-password' => 'pidtverdzhennya-parolya',
  'password' => 'parol',
  'logout' => 'vikhid',
  'report' => 'zvit',
  'lesson' => 'urok',
  'updates' => 'onovlennya',
  'frequently-asked-questions' => 'poshirenni-zapitannya',
  'privacy-policy' => 'politika-konfidentsiynosti',
  'cookie-policy' => 'politika-vikoristannya-foylive-cookie',
  'contact-us' => 'zvyazhitesya-z-namy',
  'terms-of-service' => 'umovy-korystuvannya',
];
