<?php

return [
  'title' => 'Acceso',
  'action' => 'Acceso',
  'login_redirect' => '¿No tienes una cuenta?',
  'register_redirect' => '¿Ya tienes una cuenta?',
  'failed' => 'Estas credenciales no coinciden con nuestros registros.',
  'password' => 'Estas credenciales no coinciden con nuestros registros.',
  'throttle' => 'Demasiados intentos de inicio de sesión. Por favor, inténtalo de nuevo en :seconds seconds.',
  'name' => 'Nombre',
  'provider' => 'Esta cuenta esta vinculada con :provider account.',
  'forgot_password_description' => '¿Olvidaste tu contraseña? No hay problema. Solo déjanos saber tu dirección de correo electrónico y te enviaremos un enlace de restablecimiento de contraseña por correo electrónico que te permitirá elegir una nueva.',
  'confirm_password_description' => 'Esta es un área segura de la aplicación. Por favor confirme su contraseña antes de continuar.',
  'profile_description' => 'Actualiza la información de perfil y la dirección de correo electrónico de tu cuenta.',
  'update_password_description' => 'Asegúrate de que tu cuenta esté utilizando una contraseña larga y aleatoria para mantenerla segura.',
  'delete_account_description' => 'Una vez que se elimine su cuenta, todos sus recursos y datos serán eliminados permanentemente. Antes de eliminar su cuenta, por favor descargue cualquier dato o información que desee conservar.',
  'delete_account_confirmation' => 'Una vez que se elimine tu cuenta, todos sus recursos y datos se eliminarán de forma permanente. Por favor, ingresa tu contraseña para confirmar que deseas eliminar tu cuenta de forma permanente.',
  'set_password_description' => 'Has iniciado sesión usando un proveedor de terceros como Google, Apple o LinkedIn. Para poder acceder directamente a la plataforma, establece una contraseña.',
  'onboarding_teacher_question' => '¿Por favor, dinos si te gustaría enseñar o si estás buscando tutores?',
  'onboarding_teacher_title' => '¡Bienvenido a nuestra plataforma :first_name!',
  'onboarding_not_teacher' => 'Buscando Maestros',
  'onboarding_is_teacher' => 'Quiero Enseñar',
  'approval_notice' => 'Tu actualización de imagen está siendo revisada. Será visible tan pronto como sea aprobada.',
  'approval_denied_notice' => 'Tu actualización de imagen ha sido denegada. Por favor, sube una nueva imagen que cumpla con nuestras directrices.',
  'update_profile_photo' => 'Actualizar Foto de Perfil',
  'update_email_action' => 'Confirmar Correo Electrónico',
  'update_email_description' => 'No pudimos detectar un correo electrónico de tu proveedor de autenticación. Por favor, escribe tu correo electrónico para continuar.',
  'update_email_failed' => 'Error al actualizar el correo electrónico. Probablemente ya existe en nuestro sistema.',
  'login_meta_title' => 'Iniciar Sesión en Clasora - Conéctate con Tutores de Confianza Mundialmente o Comienza a Enseñar',
  'login_meta_keywords' => 'Clasora iniciar sesión, acceso tutor, acceso estudiante, plataforma de tutoría gratuita, acceso aprendizaje en línea, acceso tutores de idiomas',
  'login_meta_description' => 'Inicia sesión en tu cuenta de Clasora para encontrar y conectarte con tutores experimentados en múltiples idiomas. 100% gratuito para estudiantes y profesores.',
  'register_meta_title' => 'Únete a Clasora - Plataforma Gratuita para Encontrar o Convertirte en Tutor',
  'register_meta_keywords' => 'Clasora registro, registrarse tutores, registrarse estudiantes, convertirse en tutor, encontrar tutor, sitio de tutoría gratuito, lecciones en línea',
  'register_meta_description' => 'Regístrate gratis en Clasora para encontrar el tutor perfecto o comenzar a ofrecer lecciones en todo el mundo. Sin tarifas, sin comisiones - solo aprender y enseñar.',
  'forgot_password_meta_title' => 'Restablecer tu Contraseña - Plataforma de Tutoría Clasora',
  'forgot_password_meta_description' => '¿Olvidaste tu contraseña? Restablece fácilmente las credenciales de tu cuenta Clasora y regresa a aprender o enseñar. Proceso de recuperación rápido y seguro.',
  'forgot_password_meta_keywords' => 'Clasora restablecer contraseña, olvidé contraseña, recuperar cuenta, restablecer acceso, recuperación cuenta tutoría, Clasora olvidé contraseña',
];
