<?php

return [
  'description_1' => 'Registrarse y publicar anuncios siempre será gratuito.',
  'native_speakers_section' => '¿Quieres aprender un idioma con un hablante nativo o un tutor extranjero? Mira estas publicaciones.',
  'choose' => 'Elija',
  'chosen' => 'Seleccionado',
  'remove' => 'Eliminar',
  'subject' => 'Asignatura',
  'choose_subject' => 'Elija una asignatura',
  'choose_tag' => 'Elija una etiqueta',
  'choose_language' => 'Elija un idioma',
  'levels_certifications' => 'Niveles y certificaciones',
  'tutor_speaks' => 'El tutor habla',
  'default' => 'Predeterminado',
  'class_location' => 'Ubicación de la clase',
  'blogs' => 'Artículos escritos por el tutor',
  'author' => 'Autor',
  'alternative_language_section' => 'Aquí hay algunas publicaciones en otros idiomas que podrían interesarte.',
  'why_choose_title' => '¿Por qué elegir Clasora?',
  'why_choose_description' => 'Clasora te conecta con tutores para clases privadas, uno a uno, tanto online como presenciales. Aprende a tu ritmo, con educadores apasionados que se preocupan por ti.',
  'why_choose_personalized_title' => 'Aprendizaje personalizado',
  'why_choose_personalized_text' => 'Cada tutor tiene su propio estilo de enseñanza. Ya sea que aprendas un idioma, te prepares para exámenes o adquieras nuevas habilidades, encuentra a la persona adecuada para ti.',
  'why_choose_affordable_title' => 'Transparente y asequible',
  'why_choose_affordable_text' => 'Sin suscripciones ni cargos ocultos. Solo pagas por lo que reservas. Los tutores se quedan con el 100% de sus ganancias.',
  'why_choose_online_local_title' => 'Online y presencial',
  'why_choose_online_local_text' => '¿Prefieres clases presenciales? Algunos tutores también ofrecen sesiones locales. Elige lo que mejor se adapte a ti.',
  'how_it_works_title' => '¿Cómo funciona?',
  'how_it_works_1_title' => '1. Buscar',
  'how_it_works_1_text' => 'Encuentra la asignatura o habilidad que quieres aprender. Usa los filtros para afinar tu búsqueda.',
  'how_it_works_2_title' => '2. Elegir',
  'how_it_works_2_text' => 'Compara tutores por reseñas, precios, idiomas y tipo de clase — online o presencial.',
  'how_it_works_3_title' => '3. Reservar',
  'how_it_works_3_text' => 'Reserva una clase individual que se ajuste a tu horario y comienza a aprender de inmediato.',
  'for_tutors_title' => 'Para tutores',
  'for_tutors_description' => 'Comparte tu conocimiento. Enseña a tu manera. Clasora te da las herramientas para hacer crecer tu negocio de tutoría — sin coste alguno.',
  'for_tutors_benefit_1' => 'Sin comisiones — te quedas con el 100% de tus ganancias',
  'for_tutors_benefit_2' => 'Crea un perfil público y escribe tu propio blog',
  'for_tutors_benefit_3' => 'Ofrece clases online o presenciales',
  'for_tutors_cta' => 'Empieza a enseñar',
];
