<?php

return [
  'register' => 'inscription',
  'about' => 'a-propos',
  'login' => 'connexion',
  'tutoring' => 'tutorat',
  'post' => 'annonce',
  'posts' => 'annonces',
  'my-posts' => 'mes-annonces',
  'my' => 'mon',
  'create' => 'creer',
  'messages' => 'messages',
  'group' => 'groupe',
  'forgot-password' => 'mot-de-passe-oublie',
  'reset-password' => 'reinitialiser-mot-de-passe',
  'verify-email' => 'vérifier-e-mail',
  'verification-notification' => 'notification-de-verification',
  'email' => 'email',
  'confirm-password' => 'confirmer-mot-de-passe',
  'password' => 'mot-de-passe',
  'logout' => 'deconnexion',
  'report' => 'rapport',
  'lesson' => 'cours',
  'updates' => 'mises-a-jour',
  'frequently-asked-questions' => 'questions-frequemment-posees',
  'privacy-policy' => 'politique-de-confidentialite',
  'cookie-policy' => 'politique-de-cookies',
  'terms-of-service' => 'conditions-generales',
  'contact-us' => 'contactez-nous',
  'update-email' => 'mettre-a-jour-email',
];
