<?php

return [
  'description_1' => 'L\'inscription et la publication d\'annonces seront toujours gratuites.',
  'native_speakers_section' => 'Vous souhaitez apprendre une langue avec un locuteur natif ou un tuteur étranger ? Consultez ces annonces.',
  'choose' => 'Choisir',
  'chosen' => 'Choisi',
  'remove' => 'Supprimer',
  'subject' => 'Matière',
  'choose_subject' => 'Choisissez une matière',
  'choose_tag' => 'Choisissez une étiquette',
  'choose_language' => 'Choisissez une langue',
  'levels_certifications' => 'Niveaux et certifications',
  'tutor_speaks' => 'Le tuteur parle',
  'default' => 'Par défaut',
  'class_location' => 'Lieu de la classe',
  'blogs' => 'Articles écrits par le tuteur',
  'author' => 'Auteur',
  'alternative_language_section' => 'Voici quelques publications étrangères qui pourraient vous intéresser.',
  'why_choose_title' => 'Pourquoi choisir Clasora ?',
  'why_choose_description' => 'Clasora vous met en relation avec des tuteurs pour des cours particuliers, en tête-à-tête — en ligne ou en présentiel. Apprenez à votre rythme, avec des enseignants passionnés qui se soucient de votre réussite.',
  'why_choose_personalized_title' => 'Apprentissage personnalisé',
  'why_choose_personalized_text' => 'Chaque tuteur a sa propre méthode. Que vous appreniez une langue, prépariez un examen ou développiez une nouvelle compétence, trouvez la personne qui vous correspond.',
  'why_choose_affordable_title' => 'Transparent & abordable',
  'why_choose_affordable_text' => 'Aucun abonnement, aucun frais caché. Payez uniquement ce que vous réservez. Les tuteurs gardent 100% de leurs gains.',
  'why_choose_online_local_title' => 'En ligne & en présentiel',
  'why_choose_online_local_text' => 'Vous préférez les cours en présentiel ? Certains tuteurs proposent aussi des séances locales. Choisissez ce qui vous convient le mieux.',
  'how_it_works_title' => 'Comment ça marche',
  'how_it_works_1_title' => '1. Rechercher',
  'how_it_works_1_text' => 'Trouvez la matière ou la compétence que vous souhaitez apprendre. Utilisez les filtres pour affiner vos préférences.',
  'how_it_works_2_title' => '2. Choisir',
  'how_it_works_2_text' => 'Comparez les tuteurs selon les avis, les prix, les langues et le type de cours — en ligne ou en présentiel.',
  'how_it_works_3_title' => '3. Réserver',
  'how_it_works_3_text' => 'Réservez un cours individuel qui s’adapte à votre emploi du temps et commencez à apprendre immédiatement.',
  'for_tutors_title' => 'Pour les tuteurs',
  'for_tutors_description' => 'Partagez vos connaissances. Enseignez à votre façon. Clasora vous donne les outils pour développer votre activité de tutorat — gratuitement.',
  'for_tutors_benefit_1' => 'Aucune commission — gardez 100% de vos gains',
  'for_tutors_benefit_2' => 'Créez un profil public et rédigez votre propre blog',
  'for_tutors_benefit_3' => 'Proposez des cours en ligne ou en présentiel',
  'for_tutors_cta' => 'Commencer à enseigner',
];
