<?php

return [
  'title' => '登录',
  'action' => '登录',
  'login_redirect' => '‌还没有帐户？',
  'register_redirect' => '已有账号？',
  'failed' => '登录信息与记录不匹配。',
  'password' => '账号或密码错误。',
  'throttle' => '登录尝试过多，请:seconds 秒后重试。',
  'name' => '姓名',
  'provider' => '当前账户已绑定 :provider账户。',
  'forgot_password_description' => '忘记密码了？别担心。只需填写您的电子邮箱，我们将立即发送密码重置链接，助您轻松设置新密码。',
  'confirm_password_description' => '重要安全验证：请再次输入账户密码。',
  'profile_description' => '更新您的账户个人资料与电子邮箱地址。',
  'update_password_description' => '为确保账户安全，请务必使用长字符且无规律的随机密码。',
  'delete_account_description' => '账户删除后，所有资源和数据将被永久删除且不可恢复。请务必在删除前下载您需要保留的任何数据。',
  'delete_account_confirmation' => '账户删除后，所有资源与数据将被永久删除且不可恢复。请输入密码确认永久删除账户。',
  'set_password_description' => '检测到您通过 Google/Apple/LinkedIn 登录，为获得完整访问权限，请设置独立登录密码。',
  'onboarding_teacher_question' => '请选择您的身份:希望授课寻找学员或需要寻找导师?',
  'onboarding_teacher_title' => ':first_name，欢迎加入我们的平台！',
  'onboarding_not_teacher' => '名师招募',
  'onboarding_is_teacher' => '我要授课',
  'approval_notice' => '图片更新审核中，审核通过后将立即展示。',
  'approval_denied_notice' => '图片更新未通过审核，请重新上传符合要求的图片。',
  'update_profile_photo' => '更换头像',
  'update_email_action' => '验证电子邮箱',
  'update_email_description' => '邮箱获取失败，请重新填写邮箱地址。',
  'update_email_failed' => '邮箱更新失败，该邮箱可能已被占用。',
  'login_meta_title' => '登录Clasora - 连接全球可信导师或开启您的教学之旅',
  'login_meta_keywords' => '登录，‌导师登录，‌学员登录，免费辅导平台，‌在线学习入口，语言导师入口',
  'login_meta_description' => '立即登录您的Clasora账户，匹配多语种资深导师并且师生均免平台费。',
  'register_meta_title' => '‌加入Clasora - 免费找导师 或免费当导师',
  'register_meta_keywords' => '注册，导师注册入驻，学员免费注册，成为认证导师，寻找辅导老师，免费辅导平台，在线课程',
  'register_meta_description' => '免费注册Clasora：精准匹配全球导师 · 0成本开启教学之旅。',
  'forgot_password_meta_title' => '‌重置密码 - Clasora辅导平台',
  'forgot_password_meta_description' => '忘记密码？一键安全重置，即刻回归学习/教学。',
  'forgot_password_meta_keywords' => '密码重置，忘记密码，账户恢复，登录信息重置，教学账户恢复，密码找回',
];
