<?php

return [
  'register' => 'zhuce',
  'about' => 'guanyu',
  'login' => 'denglu',
  'tutoring' => 'zhidao',
  'post' => 'gangwei',
  'posts' => 'youjian',
  'my-posts' => 'wodeyoujian',
  'my' => 'wode',
  'create' => 'chuangjian',
  'messages' => 'xiaoxi',
  'group' => 'tuandui',
  'forgot-password' => 'wangjimima',
  'reset-password' => 'chongzhimima',
  'verify-email' => 'yanzhengdianziyoujian',
  'verification-notification' => 'yanzhengtongzhi',
  'email' => 'dianziyoujian',
  'confirm-password' => 'querenmima',
  'password' => 'mima',
  'logout' => 'tuichu',
  'report' => 'gonggao',
  'lesson' => 'kecheng',
  'updates' => 'gengxin',
  'frequently-asked-questions' => 'changjianwenti',
  'privacy-policy' => 'yinsizhengce',
  'cookie-policy' => 'cookiezhengce',
  'update-email' => 'gengxindianziyoujian',
  'terms-of-service' => 'fuwutiaokuan',
  'contact-us' => 'lianxiwomen',
];
