<?php

return [
  'accepted' => ':attribute字段为必填项。',
  'accepted_if' => '当:other为:value时，:attribute字段为必填项。',
  'active_url' => ':attribute字段必须是有效的URL。',
  'after' => ':attribute字段必须是#date之后的日期。',
  'after_or_equal' => ':attribute字段必须是在:date之后或等于:date的日期。',
  'alpha' => ':attribute字段必须包含字母。',
  'alpha_dash' => ':attribute字段仅支持字母、数字、破折号和下划线。',
  'alpha_num' => ':attribute字段只能包含字母和数字。',
  'array' => ':attribute字段必须是数组。',
  'ascii' => ':attribute字段只能包含单字节、字母、数字字符和符号。',
  'before' => ':attribute字段必须是:date之前的日期。',
  'before_or_equal' => ':attribute字段必须是:date之前或等于:date的日期。',
  'between' => 
  [
    'array' => ':attribute字段必须包含:min和:max之间的项。',
    'file' => ':attribute字段必须介于:min和:max千字节之间。',
    'numeric' => ':attribute字段必须介于:min和:max之间。',
    'string' => ':attribute字段必须介于:min和:max字符之间。',
  ],
  'boolean' => ':attribute字段必须为true或false。',
  'can' => ':attribute字段包含未经授权的值。',
  'confirmed' => ':attribute字段确认不匹配。',
  'current_password' => '密码不正确。',
  'date' => ':attribute字段必须是有效的日期。',
  'date_equals' => ':attribute字段必须是等于:date的日期。',
  'date_format' => ':attribute字段必须与:format匹配。',
  'decimal' => ':attribute字段必须具有:decimal 十进制小数位数。',
  'declined' => '必须拒绝:attribute字段。',
  'declined_if' => '当:other为:value时，必须拒绝:attribute字段。',
  'different' => ':attribute字段和:other字段必须不同。',
  'digits' => ':attribute字段必须是:digits数字。',
  'digits_between' => ':attribute字段必须介于:min和:max数字之间。',
  'dimensions' => ':attribute字段的图像尺寸无效。',
  'distinct' => ':attribute字段具有重复值。',
  'doesnt_end_with' => ':attribute字段不得以以下值之一结尾：:values。',
  'doesnt_start_with' => ':attribute字段不得以以下值之一开头：:values。',
  'email' => ':attribute字段必须是有效的电子邮件地址。',
  'ends_with' => ':attribute字段必须以以下值之一结尾：:values。',
  'enum' => '所选的:attribute无效。',
  'exists' => '所选的:attribute无效。',
  'extensions' => ':attribute字段必须具有以下扩展名之一::values。',
  'file' => ':attribute字段必须是文件。',
  'filled' => ':attribute字段必须有一个值。',
  'gt' => 
  [
    'array' => ':attribute字段必须有多个:value项。',
    'file' => ':attribute字段必须大于:value千字节。',
    'numeric' => ':attribute字段必须大于:value。',
    'string' => ':attribute字段必须大于:value个字符。',
  ],
  'gte' => 
  [
    'array' => ':attribute字段必须包含:value项或更多项。',
    'file' => ':attribute字段必须大于或等于:value千字节。',
    'numeric' => ':attribute字段必须大于或等于:value。',
    'string' => ':attribute字段必须大于或等于:value字符。',
  ],
  'hex_color' => ':attribute字段必须是有效的十六进制颜色。',
  'image' => ':attribute字段必须是图像。',
  'in' => '所选的:attribute无效。',
  'in_array' => ':attribute字段必须存在于:other中。',
  'integer' => ':attribute字段必须是整数。',
  'ip' => ':attribute字段必须是有效的IP地址。',
  'ipv4' => ':attribute字段必须是有效的IPv4地址。',
  'ipv6' => ':attribute字段必须是有效的IPv6地址。',
  'json' => ':attribute字段必须是有效的JSON字符串。',
  'lowercase' => ':attribute字段必须小写。',
  'lt' => 
  [
    'array' => ':attribute字段必须包含少于:value的项。',
    'file' => ':attribute字段必须小于:value千字节。',
    'numeric' => ':attribute字段必须小于:value。',
    'string' => ':attribute字段必须少于:value个字符。',
  ],
  'lte' => 
  [
    'array' => ':attribute字段不能有超过:value个项。',
    'file' => ':attribute字段必须小于或等于:value千字节。',
    'numeric' => ':attribute字段必须小于或等于:value。',
    'string' => ':attribute字段必须小于或等于:value字符。',
  ],
  'mac_address' => ':attribute字段必须是有效的MAC地址。',
  'max' => 
  [
    'array' => ':attribute字段的项目数不得超过:max。',
    'file' => ':attribute字段不得大于:max KB。',
    'numeric' => ':attribute字段不得大于:max。',
    'string' => ':attribute字段不得超过:max个字符。',
  ],
  'max_digits' => ':attribute字段的位数不得超过:max。',
  'mimes' => ':attribute字段必须是类型为:values的文件。',
  'mimetypes' => ':attribute字段必须是类型为::values的文件。',
  'min' => 
  [
    'array' => ':attribute字段必须至少包含:min个项目。',
    'file' => ':attribute字段必须至少为:min KB。',
    'numeric' => ':attribute字段必须至少为:min。',
    'string' => ':attribute字段必须至少包含:min个字符。',
  ],
  'min_digits' => ':attribute字段必须至少包含:min位数字。',
  'missing' => '必须缺少:attribute字段。',
  'missing_if' => '当:other为:value时，必须缺少:attribute字段。',
  'missing_unless' => '除非:other是:value，否则:attribute字段必须缺失。',
  'missing_with' => '当:values存在时，:attribute字段必须缺失。',
  'missing_with_all' => '当:values值存在时，:attribute字段必须缺失。',
  'multiple_of' => ':attribute字段必须是:value的倍数。',
  'not_in' => '所选的 :attribute无效。',
  'not_regex' => ':attribute字段格式无效。',
  'numeric' => ':attribute字段必须是数字。',
  'password' => 
  [
    'letters' => ':attribute字段必须至少包含一个字母。',
    'mixed' => ':attribute字段必须至少包含一个大写字母和一个小写字母。',
    'numbers' => ':attribute字段必须至少包含一个数字。',
    'symbols' => ':attribute字段必须至少包含一个符号。',
    'uncompromised' => '给定的:attribute出现在数据泄漏中，请选择其他:attribute。',
  ],
  'present' => ':attribute字段必须存在。',
  'present_if' => '当:other为:value时，:attribute字段必须存在。',
  'present_unless' => '除非:other是:value，否则:attribute字段必须存在。',
  'present_with' => '当:values存在时，:attribute字段必须存在。',
  'present_with_all' => '当 :values存在时，:attribute字段必须存在。',
  'prohibited' => '禁止使用:attribute字段。',
  'prohibited_if' => '当:other为:value时，禁止使用:attribute字段。',
  'prohibited_unless' => '除非:values中有:other，否则禁止使用:attribute字段。',
  'prohibits' => ':attribute字段禁止:other出现。',
  'regex' => ':attribute字段格式无效。',
  'required' => ':attribute字段是必需的。',
  'required_array_keys' => ':attribute字段必须包含: :values的条目。',
  'required_if' => '当:other为:value时，:attribute字段是必需的。',
  'required_if_accepted' => '当接受:other时，:attribute字段是必需的。',
  'required_unless' => '除非:values中有:other，否则:attribute字段是必需的。',
  'required_with' => '当:values存在时，:attribute字段是必需的。',
  'required_with_all' => '当存在 :values时，:attribute字段是必需的。',
  'required_without' => '当:values不存在时，:attribute字段是必需的。',
  'required_without_all' => '当:values都不存在时，:attribute字段是必需的。',
  'same' => ':attribute字段必须匹配:other。',
  'size' => 
  [
    'array' => ':attribute字段必须包含:size项。',
    'file' => ':attribute字段必须为:size KB。',
    'numeric' => ':attribute字段必须为:size。',
    'string' => ':attribute字段必须是:size字符。',
  ],
  'starts_with' => ':attribute字段必须以以下值之一开头:values值。',
  'string' => ':attribute字段必须是字符串。',
  'timezone' => ':attribute字段必须是有效的时区。',
  'unique' => ':attribute已被占用。',
  'uploaded' => ':attribute上传失败。',
  'uppercase' => ':attribute字段必须大写。',
  'url' => ':attribute字段必须是有效的URL。',
  'ulid' => ':attribute字段必须是有效的ULID。',
  'uuid' => ':attribute字段必须是有效的UUID。',
  'custom' => 
  [
    'avatar' => 
    [
      'base64image' => '文件必须是有效的图像（jpeg、png、jpg、gif、svg）。',
    ],
    'atLeastOneRole' => 
    [
      'required' => '您必须至少选择一个选项。',
    ],
    'atLeastOneLocation' => 
    [
      'required' => '必须至少选择一个选项（线上或线下）。',
    ],
  ],
];
