<?php

return [
  'description_1' => '注册和发布广告终身免费。',
  'native_speakers_section' => '想从专业人士或外国导师那里学习一门语言吗？看看这些帖子。',
  'choose' => '选择',
  'chosen' => '选中',
  'remove' => '删除',
  'subject' => '主题',
  'choose_subject' => '选择主题',
  'choose_tag' => '选择标签',
  'choose_language' => '选择语言',
  'levels_certifications' => '等级和认证',
  'tutor_speaks' => '导师语录',
  'default' => '默认',
  'class_location' => '课程地点',
  'blogs' => '导师撰写的文章',
  'author' => '作者',
  'alternative_language_section' => '这里有一些您可能感兴趣的外文帖子。',
  'why_choose_title' => '为什么选择Clasora？',
  'why_choose_description' => 'Clasora为你连接一对一私人课程导师——无论是线上还是线下。跟随热情的老师，按自己的节奏学习。',
  'why_choose_personalized_title' => '个性化学习',
  'why_choose_personalized_text' => '每位导师都有独特的教学风格。无论你是学语言、备考还是提升新技能——都能找到适合你的老师。',
  'why_choose_affordable_title' => '透明且实惠',
  'why_choose_affordable_text' => '无订阅，无隐藏费用。只为你预订的课程付费。导师获得全部收入。',
  'why_choose_online_local_title' => '线上与线下',
  'why_choose_online_local_text' => '喜欢线下课程？部分导师也提供本地授课。选择最适合你的方式。',
  'how_it_works_title' => '如何运作',
  'how_it_works_1_title' => '1. 搜索',
  'how_it_works_1_text' => '找到你想学的科目或技能。用筛选器精准定位。',
  'how_it_works_2_title' => '2. 选择',
  'how_it_works_2_text' => '按评价、价格、语言和授课方式（线上/线下）对比导师。',
  'how_it_works_3_title' => '3. 预约',
  'how_it_works_3_text' => '预约适合你时间的一对一课程，立即开始学习。',
  'for_tutors_title' => '导师专属',
  'for_tutors_description' => '分享你的知识，自由教学。Clasora为你提供成长工具——完全免费。',
  'for_tutors_benefit_1' => '无佣金——收入100%归你',
  'for_tutors_benefit_2' => '创建公开档案并撰写博客',
  'for_tutors_benefit_3' => '可线上或线下授课',
  'for_tutors_cta' => '立即授课',
];
