<?php

return [
  'title' => 'Prijavi se',
  'action' => 'Prijavi se',
  'login_redirect' => 'Nemate nalog?',
  'register_redirect' => 'Već imate nalog?',
  'failed' => 'Ove informacije se ne poklapaju sa našim zapisima.',
  'password' => 'Ove informacije se ne poklapaju sa našim zapisima.',
  'throttle' => 'Previše pokušaja prijavljivanja. Molim vas, pokušajte ponovo za :seconds sekundi.',
  'name' => 'Ime',
  'provider' => 'Ovaj nalog je povezan sa :provider nalogom.',
  'forgot_password_description' => 'Zaboravili ste lozinku? Nema problema. Unesite vašu email adresu i poslaćemo vam link koji će vam omogućiti da izaberete novu lozinku.',
  'confirm_password_description' => 'Molimo potvrdite vašu lozinku pre nego što nastavite.',
  'profile_description' => 'Ažurirajte informacije o profilu i email adresu vašeg naloga.',
  'update_password_description' => 'Proverite da li vaš nalog koristi dugu, nasumičnu lozinku kako bi ostali bezbedni.',
  'delete_account_description' => 'Kada se nalog obriše, svi njegovi podaci povezani sa vašim nalogom će biti trajno obrisani. Pre nego što obrišete nalog, preuzmite sve podatke ili informacije koje želite da zadržite.',
  'delete_account_confirmation' => 'Kada se nalog obriše, svi njegovi podaci povezani sa vašim nalogom će biti trajno obrisani. Unesite lozinku da biste potvrdili da želite trajno da obrišete svoj nalog.',
  'set_password_description' => 'Prijavili ste se koristeći 3rd party provajdera kao što su Google, Apple ili Linkedin. Da biste mogli direktno pristupiti platformi postavite lozinku.',
  'onboarding_teacher_question' => 'Da li želite da predajete na našoj platformi ili tražite predavača?',
  'onboarding_teacher_title' => 'Dobro došli na platformu :first_name!',
  'onboarding_not_teacher' => 'Tražim predavača',
  'onboarding_is_teacher' => 'Želim da predajem',
  'approval_notice' => 'Promena slike zahteva odobrenje. Kada bude odobrena, slika će biti vidljiva na vašem oglasu.',
  'approval_denied_notice' => 'Vaša slika nije odobrena. Molimo postavite novu sliku koja je u skladu sa našim smernicama.',
  'update_profile_photo' => 'Ažurirajte profilnu sliku',
  'update_email_action' => 'Potvrdi email adresu',
  'update_email_description' => 'Nismo mogli da detektujemo email adresu od vašeg provajdera autentifikacije. Molimo unesite vašu email adresu da biste nastavili.',
  'update_email_failed' => 'Ažuriranje email adrese nije uspelo. Verovatno već postoji u našem sistemu.',
  'login_meta_title' => 'Prijavite se na Clasoru - Povežite se sa pouzdanim predavačima širom sveta ili počnite da predajete',
  'login_meta_keywords' => 'Clasora prijava, prijava predavač, prijava student, besplatna platforma za predavanje, prijava online učenje, prijava jezički predavači',
  'login_meta_description' => 'Prijavite se na vaš Clasora nalog da pronađete i povežete se sa iskusnim predavačima u više jezika. 100% besplatno za studente i predavače.',
  'register_meta_title' => 'Pridružite se Clasori - Besplatna platforma za pronalaženje ili postajanje predavača',
  'register_meta_keywords' => 'Clasora registracija, registracija predavači, registracija studenti, postani predavač, pronađi predavača, besplatan sajt za predavanje, online časovi',
  'register_meta_description' => 'Registrujte se besplatno na Clasori da pronađete savršenog predavača ili počnete da nudite časove širom sveta. Bez naknade, bez provizije - samo učenje i predavanje.',
  'forgot_password_meta_title' => 'Resetujte vašu lozinku - Clasora platforma za predavanje',
  'forgot_password_meta_description' => 'Zaboravili ste lozinku? Lako resetujte podatke vašeg Clasora naloga i vratite se učenju ili predavanju. Brz i siguran proces oporavka.',
  'forgot_password_meta_keywords' => 'Clasora reset lozinke, zaboravio lozinku, oporavi nalog, resetuj prijavu, oporavak naloga za predavanje, Clasora zaboravio lozinku',
];
