<?php

return [
  'description_1' => 'Registracija i postavljanje oglasa će uvek biti besplatni.',
  'native_speakers_section' => 'Želite da učite jezik od predavača koji govori maternji jezik ili da isključivo pričate na stranom jeziku? Pogledajte ove objave.',
  'choose' => 'Odaberite',
  'chosen' => 'Odabrano',
  'remove' => 'Obrišite',
  'subject' => 'Predmet',
  'choose_subject' => 'Odaberite predmet',
  'choose_tag' => 'Odaberite tag',
  'choose_language' => 'Odaberite jezik',
  'levels_certifications' => 'Nivoi i sertifikati',
  'tutor_speaks' => 'Predavač govori',
  'default' => 'Podrazumevano',
  'class_location' => 'Lokacija održavanja časa',
  'blogs' => 'Članci predavača',
  'author' => 'Autor',
  'alternative_language_section' => 'Evo nekoliko stranih postova koji bi vas mogli zanimati.',
  'why_choose_title' => 'Zašto izabrati Clasora?',
  'why_choose_description' => 'Clasora vas povezuje sa predavačima za privatne, individualne časove — i online i uživo. Učite svojim tempom, sa posvećenim edukatorima kojima je stalo do vašeg napretka.',
  'why_choose_personalized_title' => 'Prilagođeno učenje',
  'why_choose_personalized_text' => 'Svaki predavač ima svoj stil. Bilo da učite jezik, spremate ispite ili usvajate nove veštine — pronađite osobu koja vam odgovara.',
  'why_choose_affordable_title' => 'Transparentno i povoljno',
  'why_choose_affordable_text' => 'Bez pretplata i skrivenih troškova. Plaćate samo ono što rezervišete. Predavači zadržavaju 100% zarade.',
  'why_choose_online_local_title' => 'Online i uživo',
  'why_choose_online_local_text' => 'Više volite časove uživo? Mnogi predavači nude i lokalne termine. Izaberite ono što vam najviše odgovara.',
  'how_it_works_title' => 'Kako funkcioniše',
  'how_it_works_1_title' => '1. Pretraga',
  'how_it_works_1_text' => 'Pronađite predmet ili veštinu koju želite da naučite. Koristite filtere za precizniji izbor.',
  'how_it_works_2_title' => '2. Izaberite',
  'how_it_works_2_text' => 'Uporedite predavače po ocenama, cenama, jezicima i tipu časa — online ili uživo.',
  'how_it_works_3_title' => '3. Rezervišite',
  'how_it_works_3_text' => 'Rezervišite individualni čas u terminu koji vam odgovara i odmah počnite sa učenjem.',
  'for_tutors_title' => 'Za predavače',
  'for_tutors_description' => 'Podelite svoje znanje. Predajte na svoj način. Clasora vam daje alate za razvoj vašeg posla — potpuno besplatno.',
  'for_tutors_benefit_1' => 'Bez provizije — 100% zarade ostaje vama',
  'for_tutors_benefit_2' => 'Kreirajte javni profil i pišite svoj blog',
  'for_tutors_benefit_3' => 'Držite časove online ili uživo',
  'for_tutors_cta' => 'Počnite da predajete',
];
